name: PR Build & Test Railpacks

on:
  pull_request:
    branches:
      - canary

jobs:
  build:
    name: Build verification with Nixpacks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build container using Railpacks (no push)
        uses: iloveitaly/github-action-railpack@main
        with:
          push: false
